### ISSUE TITLE
AdaptiveFormatItem list was null or empty

### ISSUE THREAD

**Issue by niteshfel** [kotvertolet/youtube-jextractor#26]
com.github.kotvertolet.youtubejextractor.exception.ExtractionException: Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: AdaptiveFormatItem list was null or empty

found null when use this video : https://www.youtube.com/watch?v=ct9c20HaHMY
can you check what happen with this video

**Comment by kotvertolet** [comment]
@niteshfel Hi again! Thanks for posting this. I looked into it briefly and found out that this is a quite interesting case I've never faced before, the problem has something to do with the fact that this video in intended for children (at least youtube says that in it's responses), I need more time to investigate this, hold on.

**Comment by niteshfel** [comment]
Thanks Man :)

**Comment by kotvertolet** [comment]
@niteshfel I found what was wrong with this video, it's not because it intended for children, the problem with this vid is that it's a live stream:
![live](https://i.ibb.co/zfmz6Dz/Screenshot-3.jpg)

Live streams are also supported by my lib, but you have to treat them differently, to play live content you have to use DASH or HLS manifests. Your code will look like this:
```java
YoutubeVideoData videoData = youtubeJExtractor.extract("ct9c20HaHMY");
if (videoData.getVideoDetails().isLiveContent()) {
    String dashManifest = videoData.getStreamingData().getDashManifestUrl();
   // or use HLS manifest via getHlsManifestUrl() method
}
else {
...
}
```

Then you have to decide how to deal with manifest url, it depends on how you're gonna play audio/video content, if you are using [ExoPlayer](https://exoplayer.dev/), please refer to the [DASH](https://exoplayer.dev/dash.html) and [HLS](https://exoplayer.dev/hls.html) guides.

**Comment by niteshfel** [comment]
Thankas
