### ISSUE TITLE
Audio not available in extracted links

### ISSUE THREAD

**Issue by SharyRajpoot** [kotvertolet/youtube-jextractor#44]
I'm extracting a youtube streaming link using **adaptiveVideoStreams**  but this is only getting a video and I can't hear anything on the video. previous days when I have to implement your library 2 months ago this is working fine but now I'm not getting any audio with video.
I guess youtube has changed something inside which you have to look for and update your library.

Thanks. :-)

**Comment by kotvertolet** [comment]
@SharyRajpoot  It is expected behaviour, **adaptiveVideoStreams**  contains only video and **adaptiveAudioStreams**, as the name's implies, only audio. This is how youtube works - it have set of streams for audio and video and during playback it dinamically determines what stream to use (based on your network speed, software, hardware, codecs and so on). If you want to have audio and video at the same time and you don't want to messing around with combining audio and video, you can use **muxedStreams**.

**Comment by SharyRajpoot** [comment]
I have tried **muxedStreams** but sometimes its **null**.
Anyway, I have already managed to get audio and video separately and now it is working fine. :-)
thanks.

**Comment by kotvertolet** [comment]
@SharyRajpoot could you please tell how you did that in your case?
