### ISSUE TITLE
App Crashes on Released Build

### ISSUE THREAD

**Issue by SharyRajpoot** [kotvertolet/youtube-jextractor#49]
I have used your lib. for youtube link extraction on my app.
But when I run it crashes with this error log...

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.github.kotvertolet.youtubejextractor.models.youtube.videoData.VideoDetails.isLiveContent()' on a null object reference
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.a(SourceFile:226)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.c(SourceFile:148)
        at com.github.kotvertolet.youtubejextractor.YoutubeJExtractor.extract(SourceFile:93)
        at com.bitsnbytes.exiontv.iptv.adapter.MovieTrailerAdapter$getTrailerLink$1.run(SourceFile:62)
        at java.lang.Thread.run(Thread.java:833)

NOTE:
Everything works great with any error when I am using a debug version 
BUT
when I sign apk and generate sign apk version then this error throws by your lib.

**Comment by SharyRajpoot** [comment]
In my build/gradle file...

I have turned off / comment this line

minifyEnabled true

then the app won't crashes, it worked fine..??? I still don't understand.!!!

**Comment by kotvertolet** [comment]
@SharyRajpoot Hi! If you are using the release build of youtube-jextractor you have to know that it is already minified, but when you build your app with **minifyEnabled true** proguard tries to minify your dependencies even more, that's why you've got a such error.

Try to add the following lines into your proguard-rules.pro:
-dontwarn com.github.kotvertolet.**
-keep class com.github.kotvertolet.**
-keep interface com.github.kotvertolet.**

**Comment by SharyRajpoot** [comment]
yes, that's what I have got also those pro-guards doing this then further more I dig and found only code obfuscation to true is causing the problem. I'll try your solution as well then let you know.
