### ISSUE TITLE
I am try to solve this issue..But not able to do it

### ISSUE THREAD

**Issue by bijayaprasana-job** [kotvertolet/youtube-jextractor#61]
Extraction failed. Please, report here: https://github.com/kotvertolet/youtube-jextractor/issues. Error details: Cannot extract youtube player config, videoId was: aMm3W2xag6M

Please give me solution

**Comment by tijot123** [comment]
i had done and added a pull request for the changes but he is notr merging it

**Comment by harshmandan** [comment]
@tijot123 I saw your PRs. What are they exactly solving. I saw 4 of them. One with matcher, one with pattern. one where you have added your own cookies (I presume, from the cookies.txt file) and one where you have updated the user agent. Can you please shed some more light.

For eg., you can tell if one video wasn't working before but after your PR is. Also I don't think it is a good idea to hard-code cookies like that because they do expire after sometime.

**Comment by tijot123** [comment]
It's working after my changes.. 
Cookie which I have created is not expired.. While it expire then we can change to another cookie.. Simple as that

**Comment by harshmandan** [comment]
Again, what is working for you after the changes. The video mentioned in this issue?

**Comment by tijot123** [comment]
yeah video mentioned in this issue is working

**Comment by antonyhaman** [comment]
@harshmandan @tijot123 @bijayaprasana-job guys, please check if it's working now on 0.3.4

**Comment by tijot123** [comment]
@kotvertolet working perfect in latest build

**Comment by antonyhaman** [comment]
@tijot123 Great, closing this one
